### ISSUE TITLE
Make installable via "raco pkg install stacker"

### ISSUE THREAD

**Issue by bremner** [LuKC1024/stacker#1]
It would be helpful for this to be installable as a "normal"  racket package. This would allow a single package for  a given course to depend on all of the relevant bits and pieces. 

EDIT: With a little experimentation I see that I can specify URLs as dependencies, so perhaps the extra indirection does not add value? Feel free to close the issue in that case.

**Comment by LuKuangChen** [comment]
Thanks for the feedback! Registering this package at the Racket package catalog would certainly make the installation process more accessible. I will leave this issue open.

**Comment by LuKuangChen** [comment]
Now it is there:
https://pkgd.racket-lang.org/pkgn/package/Stacker

**Comment by shriram** [comment]
I don't see an update of the README?

**Comment by LuKuangChen** [comment]
Resolved with the latest commit f33b4ae
